// import { Navigation } from "@shared/ui";
import { Navigation } from "@shared/ui";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <header style={{ width: "100%" }}>
          <Navigation />
        </header>
        <div
          id='container'
          style={{ display: "flex", height: "100%", flexFlow: "column nowrap" }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
